// Centralized asset imports to ensure proper bundling in production builds

export const Assets = {
  githubWhite: require('./github-white.png'),
  githubBlack: require('./github-black.png'),
  gitBlack: require('./github-black.png'),
  gitWhite: require('./github-white.png'),
  codexWhite: require('./codex-white.png'),
  codexBlack: require('./codex-black.png'),
  claudeWhite: require('./claude-white.png'),
  claudeBlack: require('./claude-black.png'),
  nodeWhite: require('./node-white.png'),
  nodeBlack: require('./node-black.png'),
  mongodbWhite: require('./mongodb-white.png'),
  mongodbBlack: require('./mongodb-black.png'),
  postgresqlWhite: require('./postgresql-white.png'),
  postgresqlBlack: require('./postgresql-black.png'),
  dockerWhite: require('./docker-white.png'),
  dockerBlack: require('./docker-black.png'),
  nvmWhite: require('./nvm-white.png'),
  nvmBlack: require('./nvm-black.png'),
  githubAddSshScreen: require('./github-add-ssh-web-screen.png'),
  chromiumWhite: require('./chromium-white.png'),
  chromiumBlack: require('./chromium-black.png'),
  bunWhite: require('./bun-white.png'),
  bunBlack: require('./bun-black.png'),
  pnpmWhite: require('./pnpm-white.png'),
  pnpmBlack: require('./pnpm-black.png'),
  npmWhite: require('./npm-white.png'),
  npmBlack: require('./npm-black.png'),
  rustWhite: require('./rust-white.png'),
  rustBlack: require('./rust-black.png'),
  cppWhite: require('./cpp-white.png'),
  cppBlack: require('./cpp-black.png'),
  javaWhite: require('./java-white.png'),
  javaBlack: require('./java-black.png'),
  pythonWhite: require('./python-white.png'),
  pythonBlack: require('./python-black.png'),
  ohmyzshBlack: require('./ohmyzsh-black.png'),
};
