/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserAgreementRouteImport } from './routes/user-agreement'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as MobileAppRouteImport } from './routes/mobile-app'
import { Route as LicenseRouteImport } from './routes/license'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as EncryptionRouteImport } from './routes/encryption'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as IndexRouteImport } from './routes/index'

const UserAgreementRoute = UserAgreementRouteImport.update({
  id: '/user-agreement',
  path: '/user-agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileAppRoute = MobileAppRouteImport.update({
  id: '/mobile-app',
  path: '/mobile-app',
  getParentRoute: () => rootRouteImport,
} as any)
const LicenseRoute = LicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const EncryptionRoute = EncryptionRouteImport.update({
  id: '/encryption',
  path: '/encryption',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/encryption': typeof EncryptionRoute
  '/get-started': typeof GetStartedRoute
  '/license': typeof LicenseRoute
  '/mobile-app': typeof MobileAppRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/tasks': typeof TasksRoute
  '/user-agreement': typeof UserAgreementRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/encryption': typeof EncryptionRoute
  '/get-started': typeof GetStartedRoute
  '/license': typeof LicenseRoute
  '/mobile-app': typeof MobileAppRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/tasks': typeof TasksRoute
  '/user-agreement': typeof UserAgreementRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/encryption': typeof EncryptionRoute
  '/get-started': typeof GetStartedRoute
  '/license': typeof LicenseRoute
  '/mobile-app': typeof MobileAppRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/tasks': typeof TasksRoute
  '/user-agreement': typeof UserAgreementRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/encryption'
    | '/get-started'
    | '/license'
    | '/mobile-app'
    | '/privacy-policy'
    | '/tasks'
    | '/user-agreement'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/encryption'
    | '/get-started'
    | '/license'
    | '/mobile-app'
    | '/privacy-policy'
    | '/tasks'
    | '/user-agreement'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/encryption'
    | '/get-started'
    | '/license'
    | '/mobile-app'
    | '/privacy-policy'
    | '/tasks'
    | '/user-agreement'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  EncryptionRoute: typeof EncryptionRoute
  GetStartedRoute: typeof GetStartedRoute
  LicenseRoute: typeof LicenseRoute
  MobileAppRoute: typeof MobileAppRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TasksRoute: typeof TasksRoute
  UserAgreementRoute: typeof UserAgreementRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-agreement': {
      id: '/user-agreement'
      path: '/user-agreement'
      fullPath: '/user-agreement'
      preLoaderRoute: typeof UserAgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-app': {
      id: '/mobile-app'
      path: '/mobile-app'
      fullPath: '/mobile-app'
      preLoaderRoute: typeof MobileAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/license': {
      id: '/license'
      path: '/license'
      fullPath: '/license'
      preLoaderRoute: typeof LicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encryption': {
      id: '/encryption'
      path: '/encryption'
      fullPath: '/encryption'
      preLoaderRoute: typeof EncryptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  EncryptionRoute: EncryptionRoute,
  GetStartedRoute: GetStartedRoute,
  LicenseRoute: LicenseRoute,
  MobileAppRoute: MobileAppRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TasksRoute: TasksRoute,
  UserAgreementRoute: UserAgreementRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
