import { palette } from './palette.js'

export const lightTheme = {
  canvas: '#f4efdf',
  background: '#f4efdf',
  backgroundSecondary: '#e8dfc8',
  surface: '#fbf7ec',
  surfaceHover: '#f0e6d0',
  panel: '#fbf7ec',
  panelAlt: '#e6dcc4',
  text: '#171512',
  inkStrong: '#0d0c0a',
  textSecondary: '#4b453b',
  textTertiary: '#736a5e',
  border: '#1f1b16',
  borderStrong: '#0d0c0a',
  focusFrame: palette.bauhaus.red,
  primary: palette.bauhaus.blue,
  primaryHover: '#204cc2',
  primaryText: '#ffffff',
  accent: palette.bauhaus.red,
  accentText: '#ffffff',
  accentBlue: palette.bauhaus.blue,
  accentRed: palette.bauhaus.red,
  accentYellow: palette.bauhaus.yellow,
  success: palette.success[600],
  successBackground: palette.success[50],
  warning: palette.warning[600],
  warningBackground: palette.warning[50],
  error: palette.error[600],
  errorBackground: palette.error[50],
} as const

export const darkTheme = {
  canvas: '#12100d',
  background: '#12100d',
  backgroundSecondary: '#1d1a16',
  surface: '#1a1713',
  surfaceHover: '#28231d',
  panel: '#1a1713',
  panelAlt: '#2a241d',
  text: '#f5eedf',
  inkStrong: '#fff7e8',
  textSecondary: '#d1c4af',
  textTertiary: '#998d79',
  border: '#7d7468',
  borderStrong: '#f5eedf',
  focusFrame: '#ff6b5f',
  primary: '#4c79f0',
  primaryHover: '#6d90f4',
  primaryText: '#ffffff',
  accent: '#f05244',
  accentText: '#ffffff',
  accentBlue: '#4c79f0',
  accentRed: '#f05244',
  accentYellow: '#f2c94c',
  success: palette.success[500],
  successBackground: palette.success[700],
  warning: palette.warning[500],
  warningBackground: palette.warning[700],
  error: palette.error[500],
  errorBackground: palette.error[700],
} as const

export type SemanticTheme = typeof lightTheme
